### ISSUE TITLE
BUILDING_CYASSL is missing in cyassl.vcxproj?

### ISSUE THREAD

**Issue by jay** [cyassl/cyassl#139]
I built the CyaSSL DLL in Visual Studio 2010 using cyassl.vcxproj. To do that I had to add preprocessor define CYASSL_DLL (expected) but also BUILDING_CYASSL. I wonder if that is an oversight or intentional; I'd think you'd want BUILDING_CYASSL regardless.

**Comment by jay** [comment]
another thing I had to do was remove `extern` from the `extern __declspec(dllimport/export)` from CYASSL_DLL defines in cyassl/ctaocrypt/visibility.h

**Comment by ejohnstown** [comment]
Thank you for the issue report. I'm going to close this since it looks like you provided a pull request fixing this in our current version of this product, [wolfSSL](https://github.com/wolfSSL/wolfssl).
