### ISSUE TITLE
Implicit declaration of function 'ForceZero'

### ISSUE THREAD

**Issue by davidgfnet** [cyassl/cyassl#143]
Hello!

I'm having issues compiling cyassl after v3.5.0. I get this message:

    ctaocrypt/src/random.c: In function 'Hash_DRBG_Reseed':
    ctaocrypt/src/random.c:192:5: error: implicit declaration of function 'ForceZero' [-Werror=implicit-function-declaration]
         ForceZero(seed, sizeof(seed));
         ^
    ctaocrypt/src/random.c:192:5: error: nested extern declaration of 'ForceZero' [-Werror=nested-externs]
    ctaocrypt/src/random.c: In function 'RNG_HealthTestLocal':
    ctaocrypt/src/random.c:608:13: error: implicit declaration of function 'ConstantCompare' [-Werror=implicit-function-declaration]
                 if (ConstantCompare(check, outputA, sizeof(check)) != 0)
                 ^
    ctaocrypt/src/random.c:608:13: error: nested extern declaration of 'ConstantCompare' [-Werror=nested-externs]

I'm using gcc 4.9.2, if that matters. With version v3.5.0 it just works OK.

**Comment by toddouska** [comment]
Thanks for the report.  The current version of CyaSSL is now wolfSSL : https://github.com/wolfSSL/wolfssl

The commit that is causing problems for you was for our CyaSSL FIPS code that plugs into wolfSSL.  We'll try to resolve that but I do suggest moving to wolfSSL for current features and fixes.

Thanks.

**Comment by davidgfnet** [comment]
Hello,
I don't get it, why are both cyassl and wolfssl being mantained then?
I also see common releases... Can you explain it or point me to some docs?
Thanks

**Comment by toddouska** [comment]
Short answer, FIPS.  Without CyaSSL FIPS still being used by wolfSSL we wouldn't be changing/maintaining CyaSSL versions and tags (there would just be the final CyaSSL version).  Sorry for the confusion.

**Comment by davidgfnet** [comment]
Sorry but I'm not a crypot expert. You mean that cyassl has been authorized
by the US government and wolfssl is still pending?

**Comment by toddouska** [comment]
No problem.  Our FIPS submission is based on CyaSSL.  wolfSSL will be submitted this year, so wolfSSL currently uses CyaSSL FIPS.
